INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Afghanistan','Kabul','Asia','42,228,408','AF');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Albania','Tirana','Europe','2,882,740','AL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Algeria','Algiers','Africa','55,465','DZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Andorra','Andorra la Vella','Europe','77,006','AD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Angola','Luanda','Africa','30,809,787','AO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Antigua and Barbuda','St. John''s','America','96,286','AG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Argentina','Buenos Aires','America','44,361,150','AR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Armenia','Yerevan','Asia','2,951,745','AM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Australia','Canberra','Oceania','24,898,152','AU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Austria','Vienna','Europe','8,891,388','AT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Azerbaijan','Baku','Asia','9,949,537','AZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bahamas','Nassau','America','385,637','BS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bahrain','Manama','Asia','1,569,446','BH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bangladesh','Dhaka','Asia','161,376,708','BD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Barbados','Bridgetown','America','286,641','BB');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Belarus','Minsk','Europe','9,452,617','BY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Belgium','Brussels','Europe','11,482,178','BE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Belize','Belmopan','America','383,071','BZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Benin','Porto Novo','Africa','11,485,044','BJ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bhutan','Thimphu','Asia','62,756','BT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bolivia','Sucre','America','754,388','BO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bosnia and Herzegovina','Sarajevo','Europe','3,323,925','BA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Botswana','Gaborone','Africa','2,254,068','BW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Brazil','Brasilia','America','209,469,323','BR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Brunei','Bandar Seri Begawan','Asia','428,963','BN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Bulgaria','Sofia','Europe','7,051,608','BG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Burkina Faso','Ouagadougou','Africa','19,751,466','BF');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Burundi','Bujumbura','Africa','10,524,117','BI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Cambodia','Phnom Penh','Asia','16,249,792','KH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Cameroon','Yaoundé','Africa','25,216,267','CM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Canada','Ottawa','America','37,074,562','CA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Cape Verde','Praia','Africa','543,767','CV');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Central African Republic','Bangui','Africa','4,666,368','CF');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Chad','N''Djamena','Africa','15,477,729','TD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Chile','Santiago','America','170,499','CL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('China','Beijing','Asia','18,729,160','CN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Colombia','Bogota','America','1,427,647,786','CO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Comoros','Moroni','Africa','49,661,048','KM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Costa Rica','San José','America','4,999,441','CR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Croatia','Zagreb','Europe','4,156,405','HR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Cuba','Havana','America','11,338,134','CU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Cyprus','Nicosia','Europe','1,170,125','CY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Czech Republic','Prague','Europe','10,665,677','CZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Democratic Republic of Congo','Kinshasa','Africa','84,068,091','CD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Denmark','Copenagen','Europe','5,752,126','DK');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Djibouti','Djibouti','Africa','958,923','DJ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Dominica','Roseau','America','71,625','DM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Dominican Republic','Santo Domingo','America','10,627,141','DO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('East Timor','Dili','Oceania','1,267,974','TL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Ecuador','Quito','America','17,084,358','EC');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Egypt','Cairo','Africa','98,423,598','EG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('El Salvador','San Salvador','America','6,420,746','SV');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Equatorial Guinea','Malabo','Africa','1,308,975','GQ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Eritrea','Asmara','Africa','3,452,786','ER');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Estonia','Tallinn','Europe','1,322,920','EE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Eswatini','Mbabane','Africa','1,136,281','SZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Ethiopia','Addis Ababa','Africa','109,224,414','ET');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Fiji','Suva','Oceania','883,483','FJ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Finland','Helsinki','Europe','5,522,576','FI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('France','Paris','Europe','64,990,511','FR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Gabon','Libreville','Africa','2,119,275','GA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Gambia','Banjul','Africa','2,280,094','GM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Georgia','Tbilisi','Asia','4,002,942','GE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Germany','Berlin','Europe','83,124,418','DE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Ghana','Accra','Africa','28,206,728','GH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Greece','Athens','Europe','10,522,246','GR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Grenada','St. George''s','America','111,454','GD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Guatemala','Guatemala City','America','17,247,849','GT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Guinea','Conakry','Africa','12,414,293','GN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Guinea-Bissau','Bissau','Africa','1,874,303','GW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Guyana','Georgetown','America','779,006','GY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Haiti','Port-au-Prince','America','11,123,178','HT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Honduras','Tegucigalpa','America','9,587,522','HN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Hungary','Budapest','Europe','9,707,499','HU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Iceland','Reykjavík','Europe','336,713','IS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('India','New Delhi','Asia','1,352,642,280','IN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Indonesia','Jakarta','Asia','267,670,543','ID');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Iran','Tehran','Asia','81,800,188','IR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Iraq','Baghdad','Asia','38,433,600','IQ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Ireland','Dublin','Europe','4,818,690','IE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Israel','Jerusalem','Asia','8,381,516','IL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Italy','Rome','Europe','60,627,291','IT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Ivory Coast','Yamoussoukro','Africa','25,069,230','CI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Jamaica','Kingston','America','2,934,847','JM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Japan','Tokyo','Asia','127,202,192','JP');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Jordan','Amman','Asia','9,965,318','JO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Kazakhstan','Astana','Asia','18,319,618','KZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Kenya','Nairobi','Africa','51,392,565','KE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Kiribati','Tarawa','Oceania','115,847','KI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Korea, North','Pyongyang','Asia','4,137,312','KP');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Korea, South','Seoul','Asia','6,304,030','KR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Kosovo','Pristina','Europe','7,061,507','XK');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Kuwait','Kuwait City','Asia','1,928,459','KW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Kyrgyzstan','Bishkek','Asia','6,859,408','KG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Laos','Vientiane','Asia','2,108,328','LA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Latvia','Riga','Europe','4,818,973','LV');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Lebanon','Beirut','Asia','6,678,559','LB');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Lesotho','Maseru','Africa','37,91','LS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Liberia','Monrovia','Africa','2,801,264','LR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Libya','Tripoli','Africa','604,245','LY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Liechtenstein','Vaduz','Europe','631,636','LI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Lithuania','Vilnius','Europe','26,262,313','LT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Luxembourg','Luxembourg','Europe','604,245','LU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Madagascar','Antananarivo','Africa','26,262,313','MG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Malawi','Lilongwe','Africa','18,143,217','MW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Malaysia','Kuala Lumpur','Asia','31,528,033','MY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Maldives','Malé','Asia','515,696','MV');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Mali','Bamako','Africa','19,077,749','ML');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Malta','Valletta','Europe','439,248','MT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Marshall Islands','Majuro','Oceania','58,413','MH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Mauritania','Nouakchott','Africa','375,673','MR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Mauritius','Port Louis','Africa','4,403,313','MU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Mexico','Mexico City','America','126,190,788','MX');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Micronesia','Palikir','Oceania','112,64','FM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Moldova','Chisinau','Europe','4,051,944','MD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Monaco','Monaco','Europe','38,682','MC');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Mongolia','Ulaanbaatar','Asia','3,170,216','MN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Montenegro','Podgorica','Europe','627,809','ME');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Morocco','Rabat','Africa','36,029,093','MA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Mozambique','Maputo','Africa','29,496,004','MZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Myanmar','Naypyidaw','Asia','53,708,320','MM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Namibia','Windhoek','Africa','2,448,301','NA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Nauru','Yaren','Oceania','10,67','NR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Nepal','Kathmandu','Asia','28,095,714','NP');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Netherlands','Amsterdam','Europe','17,059,560','NL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('New Zealand','Wellington','Oceania','4,743,131','NZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Nicaragua','Managua','America','6,465,501','NI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Niger','Niamey','Africa','22,442,822','NE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Nigeria','Abuja','Africa','195,874,683','NG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('North Macedonia','Skopje','Europe','2,082,957','MK');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Norway','Oslo','Europe','5,337,962','NO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Oman','Muscat','Asia','4,829,473','OM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Pakistan','Islamabad','Asia','212,228,286','PK');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Palau','Melekeok','Oceania','17,907','PW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Palestine','East Jerusalem','Asia','4,862,979','PS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Panama','Panama City','America','4,176,869','PA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Papua New Guinea','Port Moresby','Oceania','8,606,323','PG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Paraguay','Asunción','America','6,956,066','PY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Peru','Lima','America','31,989,260','PE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Philippines','Manila','Asia','106,651,394','PH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Poland','Warsaw','Europe','37,921,592','PL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Portugal','Lisbon','Europe','10,256,193','PT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Qatar','Doha','Asia','2,781,682','QA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Republic of the Congo','Brazzaville','Africa','882,526','CG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Romania','Bucharest','Europe','19,506,114','RO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Russia','Moscow','Europe','145,734,038','RU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Rwanda','Kigali','Africa','12,301,970','RW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Saint Kitts and Nevis','Basseterre','America','52,441','KN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Saint Lucia','Castries','America','181,889','LC');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Saint Vincent and the Grenadines','Kingstown','America','110,211','VC');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Samoa','Apia','Oceania','196,129','WS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('San Marino','San Marino','Europe','33,785','SM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('São Tomé and Príncipe','São Tomé','Africa','211,028','ST');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Saudi Arabia','Riyadh','Asia','33,702,756','SA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Senegal','Dakar','Africa','15,854,323','SN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Serbia','Belgrade','Europe','8,802,754','RS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Seychelles','Victoria','Africa','97,096','SC');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Sierra Leone','Freetown','Africa','7,650,150','SL');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Singapore','Singapore','Asia','5,757,499','SG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Slovakia','Bratislava','Europe','5,453,014','SK');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Slovenia','Ljubljana','Europe','2,077,837','SI');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Solomon Islands','Honiara','Oceania','652,857','SB');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Somalia','Mogadishu','Africa','15,008,226','SO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('South Africa','Pretoria','Africa','57,792,518','SA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('South Sudan','Juba','Africa','10,975,927','SS');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Spain','Madrid','Europe','46,692,858','ES');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Sri Lanka','Sri Jayawardenapura Kotte','Asia','21,228,763','LK');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Sudan','Khartoum','Africa','41,801,533','SD');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Suriname','Paramaribo','America','575,99','SR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Sweden','Stockholm','Europe','9,971,638','SE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Switzerland','Bern','Europe','8,525,611','CH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Syria','Damascus','Asia','16,945,057','SY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Taiwan','Taipei','Asia','23,726,460','TW');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Tajikistan','Dushanbe','Asia','9,100,835','TJ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Tanzania','Dodoma','Africa','56,313,438','TZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Thailand','Bangkok','Asia','68,863,514','TH');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Togo','Lomé','Africa','7,889,093','TG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Tonga','Nukualofa','Oceania','110,589','TO');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Trinidad and Tobago','Port of Spain','America','1,389,843','TT');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Tunisia','Tunis','Africa','11,565,201','TN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Turkey','Ankara','Asia','82,340,088','TR');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Turkmenistan','Ashgabat','Asia','5,850,901','TM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Tuvalu','Funafuti','Oceania','11,508','TV');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Uganda','Kampala','Africa','42,729,036','UG');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Ukraine','Kiev','Europe','44,246,156','UA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('United Arab Emirates','Abu Dhabi','Asia','9,630,959','AE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('United Kingdom','London','Europe','67,081,000','GB');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('United States','Washington D.C.','America','327,096,265','US');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Uruguay','Montevideo','America','3,449,285','UY');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Uzbekistan','Tashkent','Asia','32,476,244','UZ');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Vanuatu','Port Vila','Oceania','292,68','VU');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Vatican City','Vatican City','Europe','801','VA');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Venezuela','Caracas','America','28,887,118','VE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Vietnam','Hanoi','Asia','95,545,962','VN');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Yemen','Sana''a','Asia','28,498,683','YE');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Zambia','Lusaka','Africa','17,351,708','ZM');
INSERT INTO country(name,capital,continent,description,name_abbr) VALUES ('Zimbabwe','Harare','Africa','14,438,802','ZW');
